version: '3.8'

services:
  web:
    build: .
    ports:
      - 8080:80
  bdd:
    image: mariadb
    environment:
      MARIADB_USER: test
      MARIADB_PASSWORD: test
      MARIADB_ROOT_PASSWORD: haha
      MARIADB_DATABASE: adrar_apirest
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
